java -jar ./compiler.jar --compilation_level=SIMPLE_OPTIMIZATIONS --jscomp_off=internetExplorerChecks \
./js/libs/phonegap/phonegap-ios.js \
./js/libs/phonegap/phonegap-zakk.js \
./js/libs/i18n/i18n-zakk.js \
./js/libs/zepto/zepto.min.js \
./js/libs/underscore/underscore-min.js \
./js/libs/backbone/backbone-min.js \
./js/libs/backbone/backbone-relational.js \
./js/libs/iscroll/iscroll.js \
./js/localModel.js \
./js/i18n/zh-tw.js \
./js/main.js \
./js/settings.js \
./js/utils.js \
./js/models/addressAndZipcode.js \
./js/models/menuData.js \
./js/models/order.js \
./js/models/shoppingCartData.js \
./js/images.js \
./js/widget/scroller.js \
./js/widget/addressSelector.js \
./js/widget/nativeSelector.js \
./js/widget/nativeAddressSelector.js \
./js/widget/loadingPanel.js \
./js/widget/accordion.js \
./js/views/storeBrief.js \
./js/views/productOption.js \
./js/views/productPanel.js \
./js/views/shoppingCartPanel.js \
./js/pages/orderTab.js \
./js/pages/historyTab.js \
./js/pages/feedbackTab.js \
./js/pages/aboutUsTab.js \
./js/pages/startPage.js \
./js/pages/storePage.js \
./js/pages/orderInfoPage.js \
./js/pages/userInfoPage.js \
./js/router.js \
--js_output_file=complied.js